- name: "apache installation"
  hosts: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: run apt-get update
      apt:
        update_cache: yes
    - name: install apache2
      apt:
       name: apache2
       state: present
    - name: start service
      systemd:
        name: apache2
        state: restarted
        