- name: uninstall mysql
  hosts: db
  become: yes
  become_user: root
  tasks:
    - name: stop mysql service
      systemd:
        name: mysql-server
        state: stopped
    - name: uninstall mysql
      apt:
        name: mysql-server
        state: absent
        purge: yes